### ISSUE TITLE
Replace componentWillReceiveProps with something else

### ISSUE THREAD

**Issue by hlolli** [scniro/react-codemirror2#152] opened 2019-08-10 23:56 UTC
Just to clear annoying warning

```
react-dom.development.js:12029 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Controlled
```

UNSAFE_ prefix can be added as a fast workaround. This warning comes with Controlled and UnControlled.

**Comment by schanzer** [comment] 2019-10-11 19:08
This feels like a dupe of #134

**Comment by scniro** [comment] 2020-01-19 16:53
@hlolli @schanzer I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by fongandrew** [comment] 2020-03-15 18:59
#176 is merged, so this should be resolved now. You'll need to update to v6.0.1 or v7

**Closed by fongandrew** 2020-03-15 18:59 UTC
Labels: help wanted
