### ISSUE TITLE
setting new scroll values not working

### ISSUE THREAD

**Issue by 0xori** [scniro/react-codemirror2#40] opened 2017-12-06 10:06 UTC
Hi, 
I'm trying to scroll programmatically using

```
const {scroll} = this.state;

<CodeMirror
                 ...
                    onScroll={(editor, data) => {
                        this.setScroll(data);
                    }}
                    scroll={scroll}
                    autoScrollCursorOnSet={false}
                />
```

where `state.scroll` is `{x,y}` .
scrolling is working fine but when I'm trying to scroll programmatically nothing happens.
I've tried also using code mirror "native" scroll ( `cm.scrollTo(x,y)` ) and it's not working.
any idea?

**Comment by scniro** [comment] 2017-12-06 13:04
@0xori Thanks for opening this up. I have peeked into this just now and I wanted to start with the manual scroll, which does appear to work okay. I was able to do so with the following...

```jsx
<Codemirror
  editorDidMount={(editor) => {
    editor.scrollTo(50, 50) // does scroll editor and also fires `onScroll`
  }}
/>
```

However, I can reproduce the failure to update the passed in `scroll` prog programatically. I can get the editor to scroll to the specified place the _first_ time, but subsequently updating the prop after mounting indeed appears to do nothing.

I'll get a fix in for this soon, hopefully in the meantime you can manually scroll as I was able to do so. I'd anticipate this being a fairly quick fix.

**Comment by 0xori** [comment] 2017-12-06 13:11
@scniro Thanks for your comment. 
I've tried and it seems that `editor.scrollTo(x, y)` indeed working for me.

**Comment by scniro** [comment] 2017-12-06 13:17
Cool - I'm happy to hear for now. I'm still going to fix the bug for the prop now and will let you know when the new release is available.

**Comment by scniro** [comment] 2017-12-06 15:38
@0xori Okay, I looked into this for a bit now and I am conflicted to make a change that this would suggest. I do have the editor now reacting to a new `scroll` prop, but, as I see in your `onScroll` callback, you are then wanting to `setState` with a new `scroll` value. This would be redundant since you don't actually need to set the new values within `onScroll` itself (I just allow codemirror to scroll naturally) - so, `onScroll` esentially is a "read only" callback to inspect the values if you wish. You'd still be able to specify a new `scroll` - but perhaps outside of the component itself e.g. perhaps you have an action which then upon completion will set the scroll somewhere specific.

I would be interested to lock this down to truly make it a controlled method, but I do not see an obvious hook to cancel the scroll event from codemirror.

I have the changes ready to go, but would like to ask if thoughts as well, and if the `editor.scrollTo` alternative is acceptable in this case, as-is.

**Comment by 0xori** [comment] 2017-12-06 15:54
@scniro Oh, now I get it, I assumed that if I'm using `scroll` then I will have to maintain the scroll state by myself. actually I didn't want to go there and I was looking for something like `editor.scrollTo` because I just need to react to several events and scroll accordingly.
I don't see any reason not to use the `editor.scrollTo`. I think it's a perfect solution.
Thanks again!

**Comment by scniro** [comment] 2017-12-06 16:30
@0xori Cool! I'll close this out for now, however I'll keep all of this in mind if I do evolve the component further into a more truly controlled implementation. That'd come with a major release, though, so no worries on getting breaking changes with minor updates.

**Closed by scniro** 2017-12-06 16:30 UTC
