### ISSUE TITLE
Consider providing `userDefinedOptions` in initial mount.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [scniro/react-codemirror2#100] opened 2018-07-04 02:36 UTC
Certain `codemirror` modes (or at least [`graphql`](https://github.com/graphql/codemirror-graphql)) use the initial configuration provided.  However, the props passed to `Controlled` are not applied initially, only in hydration, making it impossible to set those options in that mode.  Would it be possible to pass them in the initial mount?

**Comment by scniro** [comment] 2018-07-04 14:06
I'm not fully understanding the issue. Can you place provide a detailed use case, explain where you're blocked, and desired outcome. The options are [always set](https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L688), and [`hydrate`](https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L755) is always called on a mount.

**Comment by wtgtybhertgeghgtwtg** [comment] 2018-07-04 21:02
Sorry, I realize I worded that pretty poorly.  The options aren't passed to [the initial call to `codemirror`](https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L518).  They are applied later, in hydration, but that won't affect modes that use the original config, such as [`codemirror-graphql`](https://github.com/graphql/codemirror-graphql/blob/master/src/mode.js#L38-L44).  So, if I do
```
import {Controlled as CodeMirror} from 'react-codemirror2'

<CodeMirror
  value={this.state.value}
  options={{
    mode: 'graphql',
    tabSize: 2,
  }}
  onBeforeChange={(editor, data, value) => {
    this.setState({value});
  }}
  onChange={(editor, data, value) => {
  }}
/>
```
The `tabSize` won't be respected, since [the original value of the config is passed by value](https://github.com/graphql/codemirror-graphql/blob/master/src/mode.js#L43).  Although, typing this out, it certainly seems like the issue is more with them doing that than anything.

**Comment by scniro** [comment] 2018-07-05 11:41
@wtgtybhertgeghgtwtg okay I see now. Hmm, I think we can handle that on this end regardless of what they are doing, and given the speed at which that repo appears to be publishing we can be up to speed quicker over here. Give me a couple days or so to chew on this and come up with a decent solution 👍 Will report back

**Comment by wtgtybhertgeghgtwtg** [comment] 2018-07-09 00:15
I'm referring to indentation on a newline.  Since `graphql-language-server-parser` uses `tabSize` to [determine indentation](https://github.com/graphql/graphql-language-service/blob/master/packages/parser/src/onlineParser.js#L98-L99), a new line will be indented to an unexpected level if `tabSize` is not the default 4.  Sorry for being unhelpful with this.

**Comment by scniro** [comment] 2018-07-09 11:05
@wtgtybhertgeghgtwtg okay no I am even more confused because tab size 100% works on my end. `tabSize: 2` ? two spaces. `tabSize: 8`? yup, eight spaces. Double check you are requiring your files correctly?

**Comment by alexgoncharwix** [comment] 2018-07-26 13:09
I also have an issue with options aren't passed to the initial call to codemirror. They are applied later, in hydration.
In my case I use 'lint' addon. And to have lint gutter placed after linenumbers gutter I pass these options:
```
{
  ...
  gutters: ['CodeMirror-linenumbers', 'CodeMirror-lint-markers'],
}
```

Then hydration process starts and this is called eventually:
```
this.editor.setOption("gutters", ["CodeMirror-linenumbers", "CodeMirror-lint-markers"])
```

And later on codemirror side this function is called:
```
// Rebuild the gutter elements, ensure the margin to the left of the
// code matches their width.
function updateGutters(cm) {
  var gutters = cm.display.gutters, specs = cm.options.gutters;
  removeChildren(gutters);
  var i = 0;
  for (; i < specs.length; ++i) {
    var gutterClass = specs[i];
    var gElt = gutters.appendChild(elt("div", null, "CodeMirror-gutter " + gutterClass));
    if (gutterClass == "CodeMirror-linenumbers") {
      cm.display.lineGutter = gElt;
      gElt.style.width = (cm.display.lineNumWidth || 1) + "px";
    }
  }
  gutters.style.display = i ? "" : "none";
  updateGutterSpace(cm);
}
```

But! `cm.options.gutters` never gets required value and so gutters get rendered incorrectly.

I think that If options are set during initial call to CodeMirror than it would be no issues with gutters.

Why you not passing options during initial call?

**Comment by scniro** [comment] 2018-07-26 14:07
@alexgoncharwix thanks for the contribution on this. I meant to follow up but have been swamped and let this fall off 😞 I'm still wondering when hydration would never take place, though, as it should fire always on a [mount](https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L560). Like I said, I can't reproduce this locally, I've tried to do so with the graphql options and it seems to work as expected. Are you setting an initial value? Maybe that if nothing is set the hydration call never takes place?

**Comment by alexgoncharwix** [comment] 2018-07-26 15:38
Hydration is called as expected and later on `CodeMirror.updateGutters` tries to update gutters with options provided by hydration.
And I guess there is some bug in CodeMirror because `updateGutters` receives wrong `cm.options.gutters` (sometimes it gets previous options values, sometimes the order of `['CodeMirror-linenumbers', 'CodeMirror-lint-markers']` is wrong).

It's hard to tell the cause of the bug, but I tried to pass `userDefinedOptions` in initial mount and it resolved the issue completely.

**Comment by Nishchit14** [comment] 2019-06-20 10:16
I am facing the same issue of indentation, Can I help in reproducing? @scniro 

![image](https://user-images.githubusercontent.com/5078921/59841708-80ebc280-9372-11e9-8cfd-da060a863b2c.png)

**Comment by yo7** [comment] 2019-08-24 12:04
Also `inputStyle` option can only be configured as init options.

https://github.com/codemirror/CodeMirror/blob/58df15001685683f13a5f8cfb069c84c5e1afa0c/src/edit/options.js#L78

So settings inputStyle to be `textarea` in react-codemirror2 causes error on the mobile.

**Comment by scniro** [comment] 2020-01-19 16:57
@wtgtybhertgeghgtwtg @yo7 @Nishchit14 @twheys @alexgoncharwix I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Closed** 2020-05-22 14:53 UTC
Labels: enhancement, help wanted
