### ISSUE TITLE
is there any easy way to enable the addon for search, replace and highlight on search ?

### ISSUE THREAD

**Issue by skyrocker** [scniro/react-codemirror2#111] opened 2018-08-30 08:35 UTC
I am trying to enable codemirror addons in react. I have imported all search addons as mentioned in the manual. But I could not find anywhere how to enable this addons for react. 

    import 'codemirror/lib/codemirror.css';
    import 'codemirror/theme/xq-light.css';
    import 'codemirror/theme/neat.css';
    import 'codemirror/mode/javascript/javascript.js';
    import 'codemirror/addon/search/search.js';
    import 'codemirror/addon/dialog/dialog.js';
    import 'codemirror/addon/dialog/dialog.css';
    import 'codemirror/addon/search/jump-to-line.js';
    import 'codemirror/addon/search/match-highlighter.js';
    import 'codemirror/addon/search/matchesonscrollbar.css';
    import 'codemirror/addon/search/matchesonscrollbar.js';
    import 'codemirror/addon/search/searchcursor.js';
    import './ContentEditor.css';

    options = {
            mode: 'javascript',
            theme: 'xq-light',
            lineNumbers: true,
        };

    <CodeMirror
                    ...
                    options={options}
                    ...
                    onChange={...}
    />

How to enable all these addons and what props do I need to pass?

https://stackoverflow.com/questions/52089686/how-do-i-enable-addon-in-codemirror-in-react

**Comment by scniro** [comment] 2018-09-01 13:31
@skyrocker the setup looks okay, I am assuming your webpack setup is not correct. Check out the [example doc webpack setup](https://github.com/scniro/react-codemirror2/blob/master/docs/webpack.config.js). I'm closing this out as I am confident the issue is with your development setup and not in fact an issue with the core lib

**Closed by scniro** 2018-09-01 13:31 UTC

**Comment by wardellbagby** [comment] 2020-09-22 02:11
I know this is closed, but this got me for a bit there.

@scniro was right; it was the Webpack config. In my case, tree shaking was removing the imports, since I had `"sideEffects": false` in my `package.json`, which told Webpack that none of my imports had any side effects.

The fix was to change my `package.json` to have:

```
  "sideEffects": [
    "node_modules/codemirror"
  ]
```

(You might also be able to put that directly into your Webpack config instead.)
